window.PROGRAMS_DATA = [
  {
    id: "cse_bsc",
    shortName: "CSE",
    name: "B.Sc. in Computer Science & Engineering",
    faculty: "Engineering & Technology",
    level: "Undergraduate",
    durationYears: 4,
    credits: 148,
    tuition: 380000,
    intake: "3 intakes/year",
    eligibility: "HSC/Equivalent (Science preferred), minimum GPA requirements apply",
    highlights: ["Programming & Algorithms", "AI/ML basics", "Industry projects"],
    description: "A comprehensive CSE program focused on modern computing, problem solving, and software development."
  },
  {
    id: "swe_bsc",
    shortName: "SWE",
    name: "B.Sc. in Software Engineering",
    faculty: "Engineering & Technology",
    level: "Undergraduate",
    durationYears: 4,
    credits: 148,
    tuition: 365000,
    intake: "3 intakes/year",
    eligibility: "HSC/Equivalent, minimum GPA requirements apply",
    highlights: ["SDLC & Agile", "Testing & QA", "DevOps foundations"],
    description: "Focused on building reliable software systems with engineering best practices and teamwork."
  },
  {
    id: "eee_bsc",
    shortName: "EEE",
    name: "B.Sc. in Electrical & Electronic Engineering",
    faculty: "Engineering & Technology",
    level: "Undergraduate",
    durationYears: 4,
    credits: 150,
    tuition: 360000,
    intake: "3 intakes/year",
    eligibility: "HSC/Equivalent (Science), minimum GPA requirements apply",
    highlights: ["Circuits & Electronics", "Power Systems", "Embedded basics"],
    description: "Covers core electrical engineering principles with lab work and practical applications."
  },
  {
    id: "bba",
    shortName: "BBA",
    name: "Bachelor of Business Administration (BBA)",
    faculty: "Business & Entrepreneurship",
    level: "Undergraduate",
    durationYears: 4,
    credits: 120,
    tuition: 300000,
    intake: "3 intakes/year",
    eligibility: "HSC/Equivalent, minimum GPA requirements apply",
    highlights: ["Management", "Marketing", "Finance basics"],
    description: "Business fundamentals with modern skills in leadership, communication, and analytics."
  },
  {
    id: "english_ba",
    shortName: "English",
    name: "B.A. in English",
    faculty: "Humanities & Social Sciences",
    level: "Undergraduate",
    durationYears: 4,
    credits: 120,
    tuition: 260000,
    intake: "3 intakes/year",
    eligibility: "HSC/Equivalent, minimum GPA requirements apply",
    highlights: ["Literature", "Linguistics", "Communication"],
    description: "Strong foundation in English studies and communication for diverse career paths."
  },
  {
    id: "law_llb",
    shortName: "Law",
    name: "LL.B (Honours)",
    faculty: "Law",
    level: "Undergraduate",
    durationYears: 4,
    credits: 120,
    tuition: 320000,
    intake: "2-3 intakes/year",
    eligibility: "HSC/Equivalent, minimum GPA requirements apply",
    highlights: ["Core law subjects", "Moot court exposure", "Legal writing"],
    description: "Builds legal knowledge and practical legal research and communication skills."
  },
  {
    id: "cse_msc",
    shortName: "MSc CSE",
    name: "M.Sc. in Computer Science & Engineering",
    faculty: "Engineering & Technology",
    level: "Graduate",
    durationYears: 2,
    credits: 36,
    tuition: 180000,
    intake: "2-3 intakes/year",
    eligibility: "Relevant bachelor degree, minimum CGPA requirements apply",
    highlights: ["Advanced computing", "Research methods", "Thesis/Project"],
    description: "Graduate program to specialize in computing areas with research/project focus."
  },
  {
    id: "mba",
    shortName: "MBA",
    name: "Master of Business Administration (MBA)",
    faculty: "Business & Entrepreneurship",
    level: "Graduate",
    durationYears: 2,
    credits: 60,
    tuition: 220000,
    intake: "2-3 intakes/year",
    eligibility: "Relevant bachelor degree, minimum CGPA requirements apply",
    highlights: ["Strategy", "Leadership", "Business analytics"],
    description: "Career-focused MBA with modern business strategy and leadership skills."
  }
];